name: Test
on: [push, pull_request]
jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7
          gemfile: Gemfile
          elasticsearch-version: 7.9.3
        # - ruby: 2.6
        #   gemfile: test/gemfiles/activerecord52.gemfile
        #   elasticsearch_version: 7.0.0
        # - ruby: 2.5
        #   gemfile: test/gemfiles/activerecord51.gemfile
        #   elasticsearch_version: 6.8.13
        # - ruby: 2.4
        #   gemfile: test/gemfiles/activerecord50.gemfile
        #   elasticsearch_version: 6.0.0
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: ankane/setup-elasticsearch@v1
      with:
        elasticsearch-version: ${{ matrix.elasticsearch-version }}
    - run: |
        elasticsearch-plugin install analysis-kuromoji
        elasticsearch-plugin install analysis-smartcn
        elasticsearch-plugin install analysis-stempel
        elasticsearch-plugin install analysis-ukrainian
    - run: bundle exec rake test
