name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7
          gemfile: Gemfile
          elasticsearch: 7.10.0
        - ruby: 2.6
          gemfile: test/gemfiles/activerecord52.gemfile
          elasticsearch: 7.0.0
        - ruby: 2.5
          gemfile: test/gemfiles/activerecord51.gemfile
          elasticsearch: 6.8.13
        - ruby: 2.4
          gemfile: test/gemfiles/activerecord50.gemfile
          elasticsearch: 6.0.0
        - ruby: 2.7
          gemfile: test/gemfiles/mongoid7.gemfile
          mongodb: true
        - ruby: 2.6
          gemfile: test/gemfiles/mongoid6.gemfile
          mongodb: true
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        # bundler-cache: true
    - run: bundle install
    - uses: ankane/setup-elasticsearch@v1
      with:
        elasticsearch-version: ${{ matrix.elasticsearch }}
    - uses: ankane/setup-mongodb@v1
      if: ${{ matrix.mongodb }}
    - run: sudo $ES_HOME/bin/elasticsearch-plugin install analysis-nori
      if: ${{ startsWith(matrix.elasticsearch, '6.0.') }}
    - run: |
        sudo $ES_HOME/bin/elasticsearch-plugin install analysis-kuromoji
        sudo $ES_HOME/bin/elasticsearch-plugin install analysis-smartcn
        sudo $ES_HOME/bin/elasticsearch-plugin install analysis-stempel
        sudo $ES_HOME/bin/elasticsearch-plugin install analysis-ukrainian
        sudo systemctl restart elasticsearch
    - run: |
        sudo apt-get install redis-server
        sudo systemctl start redis
    - run: bundle exec rake test
